# Generated by Django 4.2.7 on 2023-11-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment", options={"verbose_name_plural": "comments"},
        ),
    ]
